title: Bruno Travassos
logo: "https://i.ibb.co/kBM0MM7/20220918-004606.jpg"
description: >
  Desenvolvedor Front-End em contínuo aprendizado. Possuo algumas certificações e diversos projetos na área e muita determinação em aprender coisas novas e de me aperfeiçoar na minha área.
  Atualmente estou aprimorando meus conhecimentos nas linguagens de Front-End(HTML, CSS, JS e ReactJS) através de novos projetos, mas estou em busca do Full-Stack com PHP e Node.JS.
  Já sou graduado em Engenharia Mecânica, e estou na minha 2ª graduação: Ciências da Computação.
  Como conhecimento adicional:
  Ótima capacidade de raciocínio lógico;
  Um bom conhecimento das regras gramaticais da Língua Portuguesa;
  Inglês nível Avançado com certificação pela ABA English;
  Conhecimentos em Redes e Pacote Office.
  <br><br>

  <a href="https://www.linkedin.com/in/bruno-travassos-4272a1175/">Perfil no LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
